version: "3.7"

services:
    csv_writer:
        image: csv_writer
        build:
            context: .
        env_file:
            - environment
        volumes:
            - type: bind
              source: ./csv
              target: /sub/csv
        networks:
            postgres_net:

networks:
   postgres_net:
#volumes:
#    <volume_name>: